services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    entrypoint: ["/bin/sh", "-c", "redis-server --daemonize yes && while ! redis-cli ping > /dev/null 2>&1; do sleep 1; done && redis-cli FLUSHALL && redis-cli shutdown && exec redis-server"]

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

volumes:
  redis_data: